- name: Select {{cinder_db_name}} database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "select * from information_schema.SCHEMATA where schema_name='{{cinder_db_name}}';"|grep -w {{cinder_db_name}}
  ignore_errors: yes
  register: info
  run_once: true

- name: Create the {{cinder_db_name}} database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "CREATE DATABASE {{cinder_db_name}};"
  ignore_errors: yes
  when: info.rc != 0
  run_once: true

- name: Grant proper access to the database
  shell: mysql -u{{root_db_user}} -p{{root_db_password}} -e "GRANT ALL PRIVILEGES ON {{cinder_db_name}}.* TO '{{cinder_db_user}}'@'{{item}}' IDENTIFIED BY '{{cinder_db_password}}';"
  with_items:
    - localhost
    - "%"
  run_once: true

- name: Check {{cinder_name}} user
  shell: source /root/admin-openrc && openstack user show {{cinder_name}}
  ignore_errors: yes
  register: user_check
  run_once: true
  
- name: Create {{cinder_name}} user
  shell: source /root/admin-openrc && openstack user create --domain default --password {{cinder_name}} {{cinder_password}}
  when: user_check.rc != 0 
  run_once: true

- name: Add the admin role to the {{cinder_name}} user and service project
  shell: source /root/admin-openrc && openstack role add --project service --user {{cinder_name}} admin
  run_once: true

- name: Check service entity
  shell: source /root/admin-openrc && openstack service show volumev3
  ignore_errors: yes
  register: service_check
  run_once: true

- name: Create the glance service entity
  shell: source /root/admin-openrc && openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3
  when: service_check.rc != 0
  run_once: true

- name: Check the Block Storage service API endpoints
  shell: source /root/admin-openrc && openstack endpoint list|grep -w cinderv3
  ignore_errors: yes
  register: endpoint_check
  run_once: true

- name: Create the Block Storage service API endpoints
  shell: source /root/admin-openrc && openstack endpoint create --region {{region_name}} volumev3 {{item}} http://{{mgnt_vip}}:8776/v3/%\(project_id\)s
  with_items:
    - public
    - internal
    - admin
  when: endpoint_check.rc != 0
  run_once: true

- name: Populate the Block Storage database
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  run_once: true
